name = "flow-app"
main = "worker.js"
compatibility_date = "2025-01-15"
account_id = "REPLACE_WITH_ACCOUNT_ID"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "flow-conversations"
preview_bucket_name = "flow-conversations-preview"

[site]
bucket = "./"
include = ["index.html", "style.css", "app.js"]
