name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: sed -i "s/REPLACE_WITH_ACCOUNT_ID/${{ secrets.CF_ACCOUNT_ID }}/g" wrangler.toml

      - run: npx wrangler r2 bucket create flow-conversations --account-id ${{ secrets.CF_ACCOUNT_ID }} || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
